name: Build and push images on tag

on:
  push:
    tags:
      - "v*.*.*" # This will trigger the workflow on tags like v0.0.1, v1.2.3, etc.

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tiagovla/sciproxy:${{ github.ref_name }} # Uses the tag name (e.g., v0.0.1)
